; PlatformIO Project Configuration File

[env:m5stack-sticks3]
board = m5stack-sticks3
monitor_speed = 115200
board_build.partitions = custom_8Mb.csv
board_upload.flash_size = 8MB
board_upload.maximum_size = 8388608
build_src_filter =${env.build_src_filter} +<../boards/m5stack-sticks3>
build_flags =
	${env.build_flags}
	-Os
	-Iboards/m5stack-sticks3
	-DCORE_DEBUG_LEVEL=5
	-DDISABLE_ALL_LIBRARY_WARNINGS
	-DUSB_as_HID=1
	-DDEVICE_NAME='"M5Stick S3"'
	-DMIC_SPM1423=1
	-DPIN_CLK=17
	-DI2S_SCLK_PIN=17
	-DI2S_DATA_PIN=16
	-DPIN_DATA=16
	-DBTN_ALIAS='"M5"'
	-DSEL_BTN=11
	-DUP_BTN=12
	-DDW_BTN=-1
	-DBTN_ACT=LOW
	-DHAS_SCREEN=1
	-DROTATION=3
	-DMINBRIGHT=160
	-DUSER_SETUP_LOADED=1
	-DST7789_2_DRIVER=1
	-DTFT_RGB_ORDER=1
	-DTFT_WIDTH=135
	-DTFT_HEIGHT=240
	-DTFT_BACKLIGHT_ON=1
	-DTFT_BL=-1
	-DTFT_RST=21
	-DTFT_DC=45
	-DTFT_MOSI=39
	-DTFT_SCLK=40
	-DTFT_CS=41
	-DTOUCH_CS=-1
	-DSMOOTH_FONT=1
	-DSPI_FREQUENCY=20000000
	-DSPI_READ_FREQUENCY=20000000
	-DSPI_TOUCH_FREQUENCY=2500000
	-DSDCARD_CS=-1
	-DSDCARD_SCK=-1
	-DSDCARD_MISO=-1
	-DSDCARD_MOSI=-1
	-DGROVE_SDA=10
	-DGROVE_SCL=9
	-DSERIAL_TX=10
	-DSERIAL_RX=9
	-DGPS_SERIAL_TX=10
	-DGPS_SERIAL_RX=9

lib_deps =
	${env.lib_deps}
	m5stack/M5Unified @ 0.2.2

lib_ignore =
	ESP8266Audio
	ESP8266SAM
	audio-driver
